### ISSUE TITLE
Multiple Definition __vector_32

### ISSUE THREAD

**Issue by Ashteroide** [MLXXXp/ArduboyTones#3]
I keep getting this error
```
Tone.cpp.o (symbol from plugin): In function `timer0_pin_port':
(.text+0x0): multiple definition of `__vector_32'
/var/folders/k4/76dlnghs21v9yfn21jz5bm8r8hwspf/T/arduino-sketch-B8F347D11FE5AC0FC6EBBAFD1BB03697/libraries/ArduboyTones/ArduboyTones.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Error during build: exit status 1
```

System:
MacOS 10.15.7
Compiler: gcc-9
Running VSCode arduino-cli
using Mr. Blinky's Homemade Arduboy library

I've downloaded ArduboyTones multiple times and keep getting the error

**Comment by MLXXXp** [comment]
It appears that you are trying to use an interrupt more than once. 

@MrBlinky provides customised libraries for use with his _Arduboy-homemade-package_, including [ArduboyTones](https://github.com/MrBlinky/Arduboy-homemade-package/tree/master/board-package-source/libraries/ArduboyTones). You should be using it in place of my "official" _ArduboyTones_ library.

This [note](https://github.com/MrBlinky/Arduboy-homemade-package/blob/master/README.md#libraries) is included in the _README.md_ file for the _Arduboy-homemade-package_:

> Libraries
This package contains all the currently available Arduboy libraries with changes for homemade Arduboys. No libraries must be installed manually. If they are, they take precedence over the homemade package libraries and must be uninstalled.


If you still have issues, I suggest you create a topic for further discussion in the [Arduboy Forum](https://community.arduboy.com/). It will be easier to help you there.

**Comment by Ashteroide** [comment]
Thanks @MLXXXp, unfortunately your suggestion didn't work, I'll make a forum post in the Arduboy community

**Comment by MLXXXp** [comment]
The problem was due to using the Arduino _tone()_ function along with including the _ArduboyTones_ library. Both want to use the same timer interrupt.

https://community.arduboy.com/t/arduboy-tones-error-solved/9362
